### ISSUE TITLE
Iniciar com BRL e aumentar BRL

### ISSUE THREAD

**Issue by k4m4h4l** [Biscoint/biscoint-arbitrage-bot#10]
Sera que è possivel colocar a opcao de utilizar o saldo maximo.
Exemplo meu saldo e 100 BRL.
e quando aparecer uma arbitragem o bot compra o BTC na corretora mais barata e vende a quantia total que comprou na que esta pagando melhor.

Assim se repete nos proximos trades sempre escolhendo o saldo total da conta e vendendo a quantia total de btcs para subir o saldo em BRL com juros composto

**Comment by mfmmeneghin** [comment]
ACredito que seja só tirar o valor e currency do arquivo config.json! por ser opcional ele nao precisa estar la!
