### ISSUE TITLE
Grupo de ajuda

### ISSUE THREAD

**Issue by k4m4h4l** [Biscoint/biscoint-arbitrage-bot#9]
Pessoal eu estou utilizando e até agora não tive problema e nem trava vamos criar um grupo para nós ajudar no telegram ou whatsapp

**Comment by jonathascarrijo** [comment]
@k4m4h4l sugiro levar esse tópico para a seção de discussão do projeto:
https://github.com/Biscoint/biscoint-arbitrage-bot/discussions
